name: Docker Build and Deploy

on:
  push:
    branches:
      - feature/ops-tacleries
    tags:
      - '*'

env:
  IMAGE_NAME: ghcr.io/xoin-devs/xoinbot

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build app
      run: |
        npm install --production

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USER }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Determine Tag Name
      id: tagname
      run: |
        if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" =~ refs/tags/ ]]; then
          TAG_NAME=$(echo "${{ github.ref }}" | awk -F'/' '{print $NF}')
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT
        else
          echo "TAG_NAME=latest-SNAPSHOT" >> $GITHUB_OUTPUT
        fi

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ steps.tagname.outputs.TAG_NAME }}
        no-cache: true

  deploy:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Production
      run: |
        echo "Déploiement de l'image Docker sur le serveur de production"

